version: '3.8'

services:
  compta:
    container_name: compta
    restart: always
    build: .
    ports:
        - 8080:80
    env_file:
      - .env
    depends_on:
      - db_compta

  db_compta:
    container_name: db_compta
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    tty: true
    volumes:
      - db_compta:/var/lib/mysql

volumes:
  db_compta:


